baseURL = "https://xu-ellen.github.io/blog/"
languageCode = "en-us"
title = "Ellen's blog"
theme = "cactus"
copyright = "Ellen Xu"
# googleAnalytics = "UA-1234-5"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  # Home page settings
  description = '''Welcome to my little corner of the Internet :)\
  I write about learning, musings, and occasionally poetry.
  '''
  mainSection = "Blog" # your main section
  mainSectionTitle = "Blog"
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 10 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "/"

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default 

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/xu-ellen"
  [[params.social]]
    name = "goodreads"
    link = "https://www.goodreads.com/user/show/139550622-ellen"
  [[params.social]]
    name = "email"
    link = "ellenjxu@gmail.com"